set echo off feed off
--Define ORACLE_SID variable
column instance_name new_value ORACLE_SID
--Assign instance_name to ORACLE_SID variable
select instance_name from v$instance;

--FSV
CREATE SMALLFILE TABLESPACE fsvdata LOGGING 
DATAFILE '/opt/oracle/oradata/&ORACLE_SID/fsvdata01.dbf' SIZE 1M REUSE AUTOEXTEND ON NEXT 1M
MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

CREATE SMALLFILE TABLESPACE fsvindex LOGGING 
DATAFILE '/opt/oracle/oradata/&ORACLE_SID/fsvindex01.dbf' SIZE 1M AUTOEXTEND ON NEXT 1M
MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL 
SEGMENT SPACE MANAGEMENT AUTO;

--SYOTOS
CREATE SMALLFILE TABLESPACE syotosdata LOGGING 
DATAFILE '/opt/oracle/oradata/&ORACLE_SID/syotosdata01.dbf' SIZE 1M REUSE AUTOEXTEND ON NEXT 1M
MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

CREATE SMALLFILE TABLESPACE syotosindex LOGGING 
DATAFILE '/opt/oracle/oradata/&ORACLE_SID/syotosindex01.dbf' SIZE 1M AUTOEXTEND ON NEXT 1M
MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL 
SEGMENT SPACE MANAGEMENT AUTO;

--DESMOS
CREATE SMALLFILE TABLESPACE desmosdata LOGGING 
DATAFILE '/opt/oracle/oradata/&ORACLE_SID/desmosdata01.dbf' SIZE 1M REUSE AUTOEXTEND ON NEXT 1M
MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

CREATE SMALLFILE TABLESPACE desmosindex LOGGING 
DATAFILE '/opt/oracle/oradata/&ORACLE_SID/desmosindex01.dbf' SIZE 1M AUTOEXTEND ON NEXT 1M
MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL 
SEGMENT SPACE MANAGEMENT AUTO;

--MUNERIS
CREATE SMALLFILE TABLESPACE munerisdata LOGGING 
DATAFILE '/opt/oracle/oradata/&ORACLE_SID/munerisdata01.dbf' SIZE 1M REUSE AUTOEXTEND ON NEXT 1M
MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

CREATE SMALLFILE TABLESPACE munerisindex LOGGING 
DATAFILE '/opt/oracle/oradata/&ORACLE_SID/munerisindex01.dbf' SIZE 1M AUTOEXTEND ON NEXT 1M
MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL 
SEGMENT SPACE MANAGEMENT AUTO;

exit;
